### ISSUE TITLE
.ISO File for users just for OS?

### ISSUE THREAD

**Issue by amanuel2** [dreamos82/DreamOs#14]
.iso file for users just for OS? Like so : https://github.com/Bone-Project/BoneOS  , when opening dreamos site says it contains malware

**Comment by inuyasha82** [comment]
Hi, i know about that, unfortunately the server weere i was hosting the site was hacked (my fault i was not updating it for too long, nor the server neither the site) and the website was infected (not only it, but all my sites on the server), so i had to shut-down the site, and probably the only thing that i can do for it, is create a website from scratch, i hope to find some  time in the coming weeks. But hopefully at least in the next days the malware screen will disappear (i'm moving everything to a new server, buit as i said earlier the website probably has to be done again from scratch). 

Anyway in theory you can build a iso file for dreamos, after you have compiled it. 

Take a look at: https://github.com/inuyasha82/DreamOs/tree/master/utils
There is the script eltorito_gen.sh  that can create an iso image. To work it needs:
1. genisoimage 
2. mkisofs
But you can run it only if you have already compiled dreamos. 

I'm not sure if that is what you are asking for. Let me know if you need more help, or i have not answered your question. 

Anyway i think that i should translate the documentation in english :D

**Comment by amanuel2** [comment]
Sick! Can you tell me how you divide by directories? Im struggling on that part now.. Your dir structure seem to be simmilar as linux : https://github.com/torvalds/linux  , FREEBSD : https://github.com/freebsd/freebsd  , And Sortix : https://gitlab.com/sortix/sortix/tree/master

**Comment by inuyasha82** [comment]
I just tried to have every component of the os into a single directory, 
So for example: 
mem -> contain all memory related sources
boot -> contain all bootloader sources
processore -> (i think i need to refactor the sources, is the italian word for cpu) will contain all cpu related sources, etc.

One exception is the utils folder that contain some utility script/programs used for some compilation/installation purposes (like the iso generation).

Anyway i think that this division in folders is quite natural when doing an os, and problably most of them have a similar structure. Anyway my original idea was to make a unix-like os. 

I think that i can start to work again on the os restrutcuturing some folders and translating the documentation.

**Comment by amanuel2** [comment]
Don't you make ISO with grub-mkrescue? Since you are using grub

**Comment by amanuel2** [comment]
Also out of the topic but why is c better than. C++ in osdev?  And why is c++better?  I think I gotta make a major refactoring of BoneOS..

**Comment by inuyasha82** [comment]
1. Don't remember/know why i don't make use of grub-mkrescue, anyway i remember i used the eltorito_format that was the easiest way to have a bootable disk. 
2. The main/honest reason? I know C, and not C++, and when i started it i was studying C. 
I think that the decision is up to you, probably you have to choose the language that you are more confident with. Because anyway writing an OS, si something that require a lot of low level programming, so use the language that you know better. 
Anyway i think that C++, maybe has the oo approach that could help in developing some part of the Os.

**Comment by amanuel2** [comment]
@inuyasha82 Ok i turned to C As you can see 😮 .  Anyways, do you know what is suppose to be put in misc folder by any chance? Is it good to put  multiboot header there?

**Comment by inuyasha82** [comment]
@amanuel2  some suggestions:
1. Choose the programming language that you know better, or you will regret very soon!
2. The directory structure is up to you, anyway "misc" refer to something that doesn't fall into other categories. 
3. In my opnion the multiboot part should be into the boot folder not in misc (but this is my opinion!). 

Again choose wisely your programming language! Don't use C just because someone else to, or for some other reason! Use the language where you feel more confident.

**Comment by amanuel2** [comment]
@inuyasha82 i know C++ More . But C Is ***IMO*** Much easier. I think i can get better at C Than i am at C++ (Not saying i will get good, because honestly no one is good at a language so much stuff to learn). Oh yeah this guy told me the same thing that i should put it in /boot.

**Comment by amanuel2** [comment]
But i use C For osdev only really. On other projects i will work on i will predominately use C++ :-)

**Comment by amanuel2** [comment]
All in all at least you need to contain an ISO File for users who aren't experienced.. I call that Normal Installation in my repo. Just for new features and such. Btw have you ever implemented ext fs? (Especially ext4)

**Comment by inuyasha82** [comment]
Unfortunately not, i already impleented a FAT fs long long time ago, and my dummy fs for testing dreamos VFS driver.
Anyway consider that the iso file should not be on your github repository. It should be hosted on your project website, or somewhere else, but not on the github repo.

**Comment by amanuel2** [comment]
@inuyasha82 Indeed. Thats in my TODO's .. I just need to get my webdev going on with the download page.. BoneOS Is in Hosted in SourceFourge mirror since we cant afford another hosting. But as you can see our download page isnt the best yet https://boneos.org/download.html .. I will soon make an update on this ISO Problem we have. (Not putting in REPO)

**Comment by inuyasha82** [comment]
Usually you should have space for your project website on sourceforge, have you checked it? 
Github too has it's website hosting service you can have a look at it: https://pages.github.com/ 

I don't think that your iso will be bigger than few mb.

**Comment by amanuel2** [comment]
Yeah. Now look at the download page 😸. Hmm you have any ideas of the biggest ISO File for an OS you have seen?(in MB)

**Comment by inuyasha82** [comment]
You can find iso images of all sizes. From few mb, to many gb. If you think that a lot of modern linux distribution are on dvd, and usually  you download them in  iso format.

**Comment by amanuel2** [comment]
Hey @inuyasha82  How is DreamOs? :D. BTW have you checked out BoneOS

**Comment by inuyasha82** [comment]
Hi @amanuel2, still sleepiing, did few commit to update indentantion/readme, but nothing more. 
Anyway haven't  checked BoneOs yet, i was busy in the past few weeks, i'll give it a look as soon as i have some free time :).

**Comment by amanuel2** [comment]
@inuyasha82 ah 😸. You know how to build grub using Windows only? Without administrator privileges.

**Comment by inuyasha82** [comment]
Unfortunately no @amanuel2 I always developed dreamos on linux! :)

**Comment by amanuel2** [comment]
ahh okay well turns out you can osdev in Cloud9 and NoVNC 😸

**Comment by inuyasha82** [comment]
no :D Just Linux! :) 
I'm a linux user since 2000 :D (And mono-linux user since ~2005)

**Comment by amanuel2** [comment]
You will change to becoming a BoneOS User. Dont Worry 😼 😸

**Comment by amanuel2** [comment]
Also is there like a github donation inteegration? Like where people can donate to a project?

**Comment by inuyasha82** [comment]
Try to follow these steps: https://gist.github.com/mw-ferretti/ed91db2c896bf91ecfe5

**Comment by amanuel2** [comment]
i dont have credit card lol im 15... Is there like a free bank i can have online?

**Comment by inuyasha82** [comment]
You can try flattr! Anyway do you need a credit card in order to register to paypal?

**Comment by amanuel2** [comment]
Dosent seem since i have a paypal

**Comment by amanuel2** [comment]
flattr reqyires money lol...  Idk how they think you posting a project so ypu can get donations and ypu have to pay them makes any sense

**Comment by amanuel2** [comment]
gitcheese. nice donation 😸. Plus some love for the cats 😹 😼

**Comment by amanuel2** [comment]
How is DreamOs going @inuyasha82 z?  Also have u thought of a configure script or handling multiple archectures?

**Comment by inuyasha82** [comment]
Hi @amanuel2  something is brewing! 
I reinstalled the dev environment on my laptop, bochs, nasm, etc... and launched it :D 
And started to have a look at the code! And as you can see now someone is contributing. 

I hope to find time to start to code it again! But maybe i must decide a roadmap first!! And how is boneos doing?

**Comment by amanuel2** [comment]
boneos is doing good. i am revising the video driver, and soon will support x86_64 😸
