### ISSUE TITLE
Remove absolute paths from bochs configuration file

### ISSUE THREAD

**Issue by inuyasha82** [dreamos82/DreamOs#20]
i.e.
vgaromimage
romimage

**Comment by Emily82** [comment]
It depends on the location of DreamOs folder, it can be anywhere so relative paths cannot be used in universal way. Maybe, do you mean using some script variable?

**Comment by inuyasha82** [comment]
Emily it is obvious that depend on the location of Dreamos (and anyway it depens mainly on the location of bochs), my idea is to add in the readme a suggested path for  bochs and dreamos and use a relative path to that default location, or maybe when you launch start.sh it will set an Environment variable with Bochs location, or look for it programmatically, I still have to decide.

**Comment by Emily82** [comment]
We could redistribute vgaromimage and romimage bochs in dreamos folder?

**Comment by inuyasha82** [comment]
I don't think is a good idea. I don't want to add binary files to the repository if not really necessary (and in this case this is not necessary)

**Comment by Emily82** [comment]
Ok

**Comment by Emily82** [comment]
If we want to use "locate" command, i made a small script that could be integrated in start.sh script.

```
#!/bin/sh
SEARCH=$(locate BIOS-bochs-latest)
OLD_IFS=$IFS     # save internal field separator
IFS='
'                # set it to newline
set -- $SEARCH   # make the result positional parameters
IFS=$OLD_IFS     # restore IFS
ROMIMAGE=$1
SEARCH=$(locate VGABIOS-lgpl-latest)
OLD_IFS=$IFS     # save internal field separator
IFS='
'                # set it to newline
set -- $SEARCH   # make the result positional parameters
IFS=$OLD_IFS     # restore IFS
VGAROMIMAGE=$1
echo $ROMIMAGE
echo $VGAROMIMAGE
```
ROMIMAGE and VGAROMIMAGE has got the first entry containing files we need.
However this solution needs 'updatedb' to be issued.

**Comment by Emily82** [comment]
I did the script to fully work making sed in .bochsrc file.
Tell me what do you think about this [script](https://github.com/Emily82/DreamOs/commit/06d655c6114a9df4a1b4bc03909778a4b59021e4)
