### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by amanuel2** [dreamos82/DreamOs#33]
Do you guys have ideas how you make the bitmap memory allocator? Im currently struggling trying to get a memory allocator..

**Comment by amanuel2** [comment]
Or like any articles explaining the implementation of physical memory allocator?

**Comment by Emily82** [comment]
For what i know a good documentation site is this http://wiki.osdev.org/Memory_Allocation

**Comment by inuyasha82** [comment]
You can have a look also here: http://wiki.unix-below.net/doku.php?id=memoria_fisica
